//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSA
{
    public partial class StartLab
    {
        /// <summary>
        /// pnlBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBack;

        /// <summary>
        /// lnkBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;

        /// <summary>
        /// litHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeading;

        /// <summary>
        /// pnlLab control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLab;

        /// <summary>
        /// lblDifficulty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDifficulty;

        /// <summary>
        /// lblTimeLimit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTimeLimit;

        /// <summary>
        /// litScenario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litScenario;

        /// <summary>
        /// pnlHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlHint;

        /// <summary>
        /// litHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHint;
    }
}
