//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSA.Student
{
    public partial class Student_MyCourses
    {
        protected global::System.Web.UI.WebControls.LinkButton lbLogout;

        protected global::System.Web.UI.WebControls.Panel pnlCoursePage;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        protected global::System.Web.UI.WebControls.Literal litMessage;

        protected global::System.Web.UI.WebControls.Repeater rptCourses;

        protected global::System.Web.UI.WebControls.Panel pnlNoEnrolled;

        protected global::System.Web.UI.WebControls.Repeater rptAvailable;

        protected global::System.Web.UI.WebControls.Panel pnlNoAvailable;

        protected global::System.Web.UI.WebControls.Panel pnlCourseDetails;

        protected global::System.Web.UI.WebControls.LinkButton btnBack;

        protected global::System.Web.UI.WebControls.Literal litCourseName;

        protected global::System.Web.UI.WebControls.Literal litCourseDescription;

        protected global::System.Web.UI.WebControls.Literal litProgress;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressFill;

        protected global::System.Web.UI.WebControls.Repeater rptChapters;

        protected global::System.Web.UI.WebControls.Panel pnlNoChapters;
    }
}