using System;
using System.Data;
using System.Data.SqlClient;

namespace CSA.DataAccess
{
    /// <summary>
    /// Data-access layer for VirtualLabs (Terminal Sandbox page).
    /// All IDs are NVARCHAR codes (e.g. LABMKQ847). New rows get their
    /// LabID auto-generated by the database default, retrieved via OUTPUT.
    /// Every query is parameterised to prevent SQL injection.
    /// </summary>
    public static class LabService
    {
        /// <summary>Labs created by an instructor, shaped for the rptLabs Repeater.</summary>
        public static DataTable GetByInstructor(string instructorId)
        {
            string sql = @"
                SELECT  vl.LabID,
                        vl.LabTitle,
                        LEFT(ISNULL(vl.Scenario, ''), 60) AS ShortDesc,
                        c.CourseName,
                        vl.Difficulty,
                        vl.ValidationType,
                        vl.IsPublished AS IsActive
                FROM    VirtualLabs vl
                INNER JOIN Courses c ON vl.CourseID = c.CourseID
                WHERE   vl.CreatedByID = @InstructorID
                ORDER BY vl.CreatedAt DESC;";

            return DBHelper.ExecuteQuery(sql,
                new SqlParameter("@InstructorID", instructorId));
        }

        /// <summary>A single lab row for editing, or null if not found.</summary>
        public static DataRow GetById(string labId)
        {
            string sql = @"
                SELECT  LabID, CourseID, LabTitle, Scenario, HintText,
                        ExpectedCommand, ValidationType, Difficulty,
                        TimeLimitMinutes, IsPublished
                FROM    VirtualLabs
                WHERE   LabID = @LabID;";

            DataTable dt = DBHelper.ExecuteQuery(sql,
                new SqlParameter("@LabID", labId));

            return dt.Rows.Count > 0 ? dt.Rows[0] : null;
        }

        /// <summary>
        /// Inserts a new lab (labId null/empty) or updates an existing one.
        /// Returns the LabID (the DB-generated code on insert).
        /// </summary>
        public static string Save(
            string labId, string instructorId, string courseId,
            string title, string instructions, string hint,
            string validationKey, string validationType,
            string difficulty, int? timeLimitMinutes, bool isActive)
        {
            SqlParameter[] p = new[]
            {
                new SqlParameter("@CourseID",         courseId),
                new SqlParameter("@LabTitle",         title),
                new SqlParameter("@Scenario",         (object)instructions ?? DBNull.Value),
                new SqlParameter("@HintText",         string.IsNullOrWhiteSpace(hint) ? (object)DBNull.Value : hint),
                new SqlParameter("@ExpectedCommand",  validationKey),
                new SqlParameter("@ValidationType",   validationType),
                new SqlParameter("@Difficulty",       difficulty),
                new SqlParameter("@TimeLimitMinutes", (object)timeLimitMinutes ?? DBNull.Value),
                new SqlParameter("@IsPublished",      isActive),
                new SqlParameter("@CreatedByID",      instructorId)
            };

            if (string.IsNullOrEmpty(labId))
            {
                // INSERT - generate the LabID in C# and insert it explicitly.
                string newId = CodeHelper.Generate("LAB");

                string insert = @"
                    INSERT INTO VirtualLabs
                        (LabID, CourseID, LabTitle, Scenario, HintText, ExpectedCommand,
                         ValidationType, Difficulty, TimeLimitMinutes, IsPublished, CreatedByID)
                    VALUES
                        (@LabID, @CourseID, @LabTitle, @Scenario, @HintText, @ExpectedCommand,
                         @ValidationType, @Difficulty, @TimeLimitMinutes, @IsPublished, @CreatedByID);";

                SqlParameter[] pInsert = new SqlParameter[p.Length + 1];
                p.CopyTo(pInsert, 0);
                pInsert[p.Length] = new SqlParameter("@LabID", newId);

                DBHelper.ExecuteNonQuery(insert, pInsert);
                return newId;
            }
            else
            {
                // UPDATE - ownership enforced via CreatedByID.
                string update = @"
                    UPDATE VirtualLabs SET
                        CourseID         = @CourseID,
                        LabTitle         = @LabTitle,
                        Scenario         = @Scenario,
                        HintText         = @HintText,
                        ExpectedCommand  = @ExpectedCommand,
                        ValidationType   = @ValidationType,
                        Difficulty       = @Difficulty,
                        TimeLimitMinutes = @TimeLimitMinutes,
                        IsPublished      = @IsPublished,
                        UpdatedAt        = GETDATE()
                    WHERE LabID = @LabID AND CreatedByID = @CreatedByID;";

                SqlParameter[] pUpdate = new SqlParameter[p.Length + 1];
                p.CopyTo(pUpdate, 0);
                pUpdate[p.Length] = new SqlParameter("@LabID", labId);

                DBHelper.ExecuteNonQuery(update, pUpdate);
                return labId;
            }
        }

        /// <summary>Deletes a lab only if it belongs to the instructor.</summary>
        public static int Delete(string labId, string instructorId)
        {
            string sql = @"
                DELETE FROM VirtualLabs
                WHERE LabID = @LabID AND CreatedByID = @InstructorID;";

            return DBHelper.ExecuteNonQuery(sql,
                new SqlParameter("@LabID", labId),
                new SqlParameter("@InstructorID", instructorId));
        }

        /// <summary>Courses owned by an instructor, for the ddlCourse dropdown.</summary>
        public static DataTable GetCoursesForInstructor(string instructorId)
        {
            string sql = @"
                SELECT CourseID, CourseName
                FROM   Courses
                WHERE  InstructorID = @InstructorID
                ORDER BY CourseName;";

            return DBHelper.ExecuteQuery(sql,
                new SqlParameter("@InstructorID", instructorId));
        }

        /// <summary>
        /// Test helper: returns the first lecturer's UserID so the page works
        /// before login is wired up. Remove once real sessions are in place.
        /// </summary>
        public static string GetAnyLecturerId()
        {
            string sql = @"
                SELECT TOP 1 u.UserID
                FROM   Users u
                INNER JOIN Roles r ON u.RoleID = r.RoleID
                WHERE  r.RoleName = 'Lecturer'
                ORDER BY u.UserID;";

            object o = DBHelper.ExecuteScalar(sql);
            return o?.ToString();
        }
    }
}